JobWallet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from api import urls as api_urls

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='records/', permanent=True)),
    path('records/', include('records.urls')),
    path('analysis/', include('analysis.urls', namespace='analysis')),
    path('accounts/login', RedirectView.as_view(url='login', permanent=True)),
    path('api/', include('api.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))

    # path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from api import views
from api.serializers import PartInstanceSerializer
from api.views import UserList, UserDetail, PartInstanceList, PartInstanceDetail, OperationList
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', views.api_root),
    path('users', views.UserList.as_view(), name='user-list'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    path('parts', views.PartInstanceList.as_view(), name='part-list'),
    path('parts/<str:serial_number>', views.PartInstanceDetail.as_view(), name='part-detail'),
    path('operations', views.OperationList.as_view(), name='operation-list'),
    path('add-operation', views.AddOperation.as_view(), name='add-operation'),
    path('operations/<str:operation>', views.OperationDetail.as_view(), name='operation-rud'),
]

records/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', LoginView.as_view(), name='login' ),
    path('accounts/login', views.not_logged_in, name='not_logged_in'),
    path('logout', LogoutView.as_view(), name='logout' ),
    path('index', views.index, name='index' ),
    path('search-result', views.search, name='search'),
    path('add_operation', views.add_operation, name='add_operation' ),
    path('create_wallet', views.create_job_wallet, name='create_wallet'),
    path('parts', views.PartListView.as_view(), name='parts'),
    path('customers', views.CustomerListView.as_view(), name='customers'),
    path('operations', views.OperationListView.as_view(), name='operations'),
    path('wallets', views.WalletListView.as_view(), name='wallets'),
    path('wallet/<int:pk>', views.WalletDetailView.as_view(), name='wallet-detail'),
    path('part/<int:pk>', views.PartDetailView.as_view(), name='part-detail'),
    path('customer/<int:pk>', views.CustomerDetailView.as_view(), name='customer-detail'),
    path('operation/<int:pk>', views.OperationDetailView.as_view(), name='operation-detail'),
    path('partinstance/<int:pk>', views.PartInstanceDetailView.as_view(), name='partinstance-detail'),
    path('instances', views.PartInstanceListView.as_view(), name='instances'),
    path('create_job_wallet', views.create_job_wallet, name='create_job_wallet'),
    path('add_operation/<int:pk>', views.add_operation, name='add_operation_to_part' ),
]

records/models.py
from django.db import models
from django.forms import ModelForm
from .constants import PART_DESCRIPTION, OPERATIONS
from django.contrib.auth.models import User
from django.urls import reverse


class Customer(models.Model):
    CUSTOMERS = (
        ('McLaren', 'McLaren'),
        ('Ferrari', 'Ferrari'),
        ('Morgan', 'Morgan'),
        ('Maserati', 'Maserati'),
    )
    customer = models.CharField(max_length=120, choices=CUSTOMERS, default='Customer')

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('customer-detail', args=[str(self.id)])

    def __str__(self):
        return self.customer


class Part(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    FGcode = models.CharField(max_length=10)

    class Meta:
        ordering = ['FGcode']

    def description(self):
        description_text = [fg[0] for fg in PART_DESCRIPTION if fg[1] == str(self.FGcode)]
        return description_text[0]

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('part-detail', args=[str(self.id)])

    def __str__(self):
        return self.FGcode


class PartInstance(models.Model):
    job_wallet = models.ForeignKey('Wallet', related_name='wallet_parts', on_delete=models.CASCADE, null=True)
    part_origin = models.ForeignKey(Part, related_name='parts', on_delete=models.CASCADE, null=True)
    serial_number = models.CharField(max_length=11)

    class Meta:
        ordering = ['serial_number']

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('partinstance-detail', args=[str(self.id)])

    def __str__(self):
        return self.serial_number


class Operation(models.Model):
    owner = models.ForeignKey('auth.User', related_name='operations', on_delete=models.CASCADE, default=1)
    processed_part = models.ForeignKey(PartInstance, related_name='operations', on_delete=models.CASCADE, null=True)
    operation_name = models.CharField(max_length=120, choices=OPERATIONS, unique=True)
    date_signed = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(null=True,  blank=True, max_length=240 )
    operator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS = (('Passed', 'Passed'), ('Scrapped', 'Scrapped'), ('Quarantined', 'Quarantined'))
    operation_status = models.CharField(max_length=120, choices=STATUS, default='What is the part status?')

    class Meta:
        ordering = ['operation_name']

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('operation-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.operation_name

    def save(self, *args, **kwargs):
        super(Operation, self).save(*args, **kwargs)


class Wallet(models.Model):
    order_number = models.CharField(max_length=7)
    order_quantity = models.IntegerField(verbose_name='quantity', default=0)
    customer_name = models.ForeignKey(Customer, related_name='wallets', on_delete=models.CASCADE, null=True)
    part_FG = models.ForeignKey(Part, related_name='part_fgs', on_delete=models.CASCADE, null=True)
    part_id = models.CharField(max_length=120, default='')
    pack_number = models.CharField(max_length=10)
    traceability_required = models.BooleanField(default=True)

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('wallet-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.order_number

records/forms.py
from django import forms
from .models import Operation, Part, Customer, Wallet

class AddOperationModelForm(forms.ModelForm):
    class Meta:
        model = Operation
        fields = (
            'operation_name',
            'comments',
            'operation_status'
        )
class CreateJobWalletModelForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = (
            'order_number',
            'order_quantity',
            'customer_name',
            'part_FG',
            'part_id',
            'pack_number',
            'traceability_required'
        )

class SearchForm(forms.Form):
    # customer = forms.CharField(required=False)
    # part_FG = forms.CharField(required=False)
    serial_number = forms.CharField(required=False)
    # operator = forms.CharField(required=False)
    # date = forms.CharField(required=False)

records/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Customer, Part, PartInstance, Operation, Wallet
from django.views import generic
from .forms import AddOperationModelForm, CreateJobWalletModelForm, SearchForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.


def index(request):

    if request.user.is_authenticated:
        num_parts = Part.objects.all().count()
        num_customers = Customer.objects.all().count()

        context = {
            'num_part': num_parts,
            'num_customers': num_customers,
        }
        print(num_customers, num_parts)
        return render(request, 'index.html', context)
    else:
        return redirect('login')



@login_required
def add_operation(request, pk):
    form = AddOperationModelForm()
    user = request.user
    if request.method == 'POST':
        print('received post request')
        form = AddOperationModelForm(request.POST)
        if form.is_valid():
            print('The form is valid')
            print(form.cleaned_data)
            Operation.objects.create(
                processed_part=PartInstance.objects.get(pk=pk),
                operation_name=form.cleaned_data['operation_name'],
                date_signed=Operation.date_signed,
                comments=form.cleaned_data['comments'],
                operator=user,
                operation_status=form.cleaned_data['operation_status']
            )
        return redirect('index')

    context = {
        'form': form,
        'user': user
    }
    return render(request, 'add_operation.html', context)


@login_required
def create_job_wallet(request):
    form = CreateJobWalletModelForm()

    if request.method == 'POST':
        print('received post request')
        form = CreateJobWalletModelForm(request.POST)
        if form.is_valid():
            print('The form is valid')
            print(form.cleaned_data)
            new_wallet = Wallet.objects.create(
                order_number=form.cleaned_data['order_number'],
                order_quantity=form.cleaned_data['order_quantity'],
                customer_name=form.cleaned_data['customer_name'],
                part_FG=form.cleaned_data['part_FG'],
                part_id=form.cleaned_data['part_id'],
                pack_number=form.cleaned_data['pack_number'],
                traceability_required=form.cleaned_data['traceability_required']
            )
            parts_list = []
            order_quantity = form.cleaned_data['order_quantity']
            order_number = form.cleaned_data['order_number']
            for i in range(1, order_quantity + 1):
                if i < 10:
                    single_number = '0' + str(i) + '-' + str(order_number)

                else:
                    single_number = str(i) + '-' + str(order_number)
                parts_list.append(single_number)
            for number in parts_list:
                PartInstance.objects.create(job_wallet=new_wallet,
                                            part_origin=form.cleaned_data['part_FG'], serial_number=number)
            print(parts_list)

        return redirect('index')

    context = {
        'form': form
    }

    return render(request, 'create_job_wallet.html', context)

@login_required()
def search(request):

    parts = None
    if request.method == 'POST':
        searched = request.POST['searched']
        parts = PartInstance.objects.filter(serial_number__contains=searched)
    context = {
        'parts': parts
    }

    return render(request, 'search_results.html', context)

# def logout(request):
#     try:
#         del request.session['member_id']
#     except KeyError:
#         return HttpResponse("You're logged out.")
#     return redirect("login")

def not_logged_in(request):
    return render(request, 'not_logged_in.html')

decorators = [never_cache, login_required]

@method_decorator(decorators, name='dispatch')
class PartListView(LoginRequiredMixin, generic.ListView):
    model = Part

@method_decorator(decorators, name='dispatch')
class PartDetailView(LoginRequiredMixin, generic.DetailView):

    model = Part

@method_decorator(decorators, name='dispatch')
class CustomerListView(LoginRequiredMixin, generic.ListView):

    model = Customer

@method_decorator(decorators, name='dispatch')
class CustomerDetailView(LoginRequiredMixin, generic.DetailView):

    model = Customer

@method_decorator(decorators, name='dispatch')
class OperationDetailView(LoginRequiredMixin, generic.DetailView):

    model = Operation

@method_decorator(decorators, name='dispatch')
class SearchResultsView(LoginRequiredMixin, generic.ListView):
    model = Part
    template_name = 'search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Part.objects.filter(name__icontains=query)

        return object_list

@method_decorator(decorators, name='dispatch')
class OperationListView(LoginRequiredMixin, generic.ListView):

    model = Operation

@method_decorator(decorators, name='dispatch')
class PartInstanceListView(LoginRequiredMixin, generic.ListView):

    model = PartInstance

@method_decorator(decorators, name='dispatch')
class PartInstanceDetailView(LoginRequiredMixin, generic.DetailView):

    model = PartInstance

@method_decorator(decorators, name='dispatch')
class WalletListView(LoginRequiredMixin, generic.ListView):

    model = Wallet

@method_decorator(decorators, name='dispatch')
class WalletDetailView(LoginRequiredMixin, generic.DetailView):

    model = Wallet

records/templates/records/customer_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1 style="text-align:center">{{ customer }} </h1>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <p><strong>Parts:</strong></p>

      {% if customer.part_set.all %}

      {% for part in customer.part_set.all %}

      <hr>
      <p><a href="{{ part.get_absolute_url }}">{{ part }} {{ part.description }}</a></p>

      {% endfor %}

      {% else %}
      <p>There are no {{ part.FGcode }} {{ part.customer }} {{ part.description }} parts in the records.</p>
      {% endif %}
    </div>

    <div class="col-sm">

      <p><strong>Wallets:</strong></p>
      {% if customer.wallets.all %}

      {% for wallet in customer.wallets.all %}

      <hr>
      <p><a href="{{ wallet.get_absolute_url }}">{{ wallet.part_FG }} Number: {{ wallet }}</a></p>

      {% endfor %}

      {% else %}
      <p>There are no {{ wallet.customer_name }} wallets in the records.</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}k %}l>

records/templates/records/customer_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="text-align:center">Customers</h1>
  {% if customer_list %}

    {% for customer in customer_list %}
      <hr>
      <p><a href="{{ customer.get_absolute_url }}">{{ customer.customer}}</a></p>

    {% endfor %}

  {% else %}
    <p>There are no customers in the records.</p>
  {% endif %}
{% endblock %}

records/templates/records/operation_detail.html
{% block content %}
  <h1>{{ operation.operation_name }} </h1>

  <p><strong>Operation:</strong> <a href="{{ part.operation.get_absolute_url }}"></a>{{ operation.operation_name }}</p> <!-- author detail link not yet defined -->
  <p><strong>Date:</strong> {{ operation.date_signed }}</p>
  <p><strong>Operator:</strong> {{ operation.operator }}</p>
  <p><strong>Status</strong> {{ operation.operation_status}}</p>
  <p><strong>Comments:</strong> {{ operation.comments }}</p>

{% endblock %}

records/templates/records/operation_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="text-align:center"}>Operation List</h1>
  {% if operation_list %}
  <ul>
    {% for entry in operation_list %}
      <li>
        <a href="{{ entry.get_absolute_url }}">{{ entry.operation_name }}</a>
        ({{entry.part.FGcode}}, {{entry.part.description}}, {{entry.part.serial_number}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no parts in the records.</p>
  {% endif %} 
{% endblock %}

records/templates/records/part_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="text-align:center">{{ part.customer }} {{ part.description }}</h1>

  <p><strong>Customer:</strong> <a href="{{ part.customer.get_absolute_url }}">{{ part.customer}}</a> <!-- author detail link not yet defined -->
  <p><strong>FGcode:</strong> {{ part.FGcode }}</p>
  <p>See operations details</p>
  <p><strong>Serial Number:</strong></p>


  {% if part.parts.all %}

  {% for part in part.parts.all %}

  <hr>
  <p><a href="{{ part.get_absolute_url }}">{{ part.serial_number }}</a></p>

  {% endfor %}

  {% else %}
  <p>There are no {{ part.FGcode }} {{ part.customer }} {{ part.description }} parts in the records.</p>
  {% endif %}
{% endblock %}

records/templates/records/part_form.html
{% extends "base_generic.html" %}
{% block content %}

<body>
    <form >
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
</body>
{% endblock %}

records/templates/records/part_list.html
{% extends "base_generic.html" %}


{% block content %}
<div class="container">
  <h1 style="text-align:center">Parts List</h1>
  {% if part_list %}
  <ul>
    {% for part in part_list %}

      <li>{{part.customer }}  <a href="{{ part.get_absolute_url }}">{{part.FGcode}}</a>
        ({{part.description}})
        <hr>
      </li>

    {% endfor %}
  </ul>
  {% else %}
    <p>There are no parts in the records.</p>
  {% endif %} 
{% endblock %}
  </div>

records/templates/records/partinstance_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
  <h1> Serial Number: {{ partinstance.serial_number }}</h1>
  <h2> {{ partinstance.part_origin}}</h2>
    <h2> {{ partinstance.part_origin.customer }}</h2>
    <h2> {{ partinstance.part_origin.description }}</h2>

  <p><strong>Operations:</strong> </p>


  {% if partinstance.operations.all %}
    <a href="{% url 'add_operation_to_part' pk=partinstance.pk %}">Add/Sign New Operation</a>

  {% for op in partinstance.operations.all %}

  <hr>
 <h3>{{ op.operation_name }}</h3>
  <p><strong>Status:</strong>  {{ op.operation_status }}</p>
  <p><strong>Operator:</strong>  {{op.operator }}</p>
  <p><strong>Comments:</strong>  {{ op.comments }}</p>
  <p><strong>Date:</strong> {{ op.date_signed }}</p>


  {% endfor %}

  {% else %}
  <p>There are no operation records for this part.</p>
    <a href="{% url 'add_operation_to_part' pk=partinstance.pk %}">Add/Sign New Operation</a>
  {% endif %}

{% endblock %}
    </div>

records/templates/records/partinstance_list.html
part instance

records/templates/records/wallet_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
  <h1 style="text-align:right; font-family:Arial-Black" >ORDER NUMBER:  {{ wallet.order_number }} </h1>
  <hr>

<p><strong>Customer: {{ wallet.customer_name}}</strong></p>
<p><strong>FG Code: {{ wallet.part_FG}}</strong></p>
<p><strong>{{ wallet.part_FG.description}}</strong></p>
<p><strong>Part ID: {{ wallet.part_id}}</strong></p>
<p><strong>Pack Number: {{ wallet.pack_number}}</strong></p>

{% if wallet.wallet_parts.all %}

{% for part in wallet.wallet_parts.all %}
 <hr>
    <p class="p-serials"><a href="{{ part.get_absolute_url }}">{{ part.serial_number }}</a></p>




{% endfor %}
{% endif %}
{% endblock %}
        </div>

records/templates/records/wallet_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="text-align:center">Wallets</h1>
  {% if wallet_list %}

    {% for wallet in wallet_list %}
      <hr>
      <p><a href="{{ wallet.get_absolute_url }}">{{ wallet.customer_name }}  {{ wallet.part_FG }}  <strong>{{ wallet }}</strong></a></p>

    {% endfor %}

  {% else %}
    <p>There are no Job Wallets in the records.</p>
  {% endif %}
{% endblock %}l>